name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.8.x
    - name: submodules-init
      uses: snickerbockers/submodules-init@v4
    - name: Restore dependencies
      working-directory: Project-Aurora
      run: dotnet restore
    - name: Build
      working-directory: Project-Aurora
      run: dotnet build --no-restore
    - name: Test
      working-directory: Project-Aurora
      run: dotnet test --no-build --verbosity normal
